# version: "3.8"

# services:
#   frontend:
#     build: .
#     container_name: inspireher-container
#     ports:
#       - "3000:80"
#     restart: always
version: "3.8"

services:
  frontend:
    build: .
    container_name: inspireher-container
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: inspireher-backend
    expose:
      - "8000"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    image: postgres:15
    container_name: inspireher-db
    restart: always
    environment:
      POSTGRES_USER: inspireher
      POSTGRES_PASSWORD: inspireherpassword
      POSTGRES_DB: inspireherdb
    expose:
      - "5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: inspireher-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: inspireher-grafana
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: inspireher-cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
