# version: "3.8"

# services:
#   frontend:
#     build: .
#     container_name: inspireher-container
#     ports:
#       - "3000:80"
#     restart: always
version: "3.8"

services:
  frontend:
    build: .
    container_name: inspireher-container
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: inspireher-backend
    expose:
      - "8000"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    image: postgres:15
    container_name: inspireher-db
    restart: always
    environment:
      POSTGRES_USER: inspireher
      POSTGRES_PASSWORD: inspireherpassword
      POSTGRES_DB: inspireherdb
    expose:
      - "5432"